# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('.'))
#import sphinx_theme

# -- Project information -----------------------------------------------------

project = 'कहानियों का संग्रह'
copyright = '2020, pooja'
author = 'pooja'

# The full version, including alpha/beta/rc tags
release = '1.0'

html_show_sphinx = False

html_add_permalinks = ""

html_show_sourcelink = False
# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'hi'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

source_suffix = '.rst'

master_doc = 'index'
# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = "stanford_theme"
#html_theme_path = [sphinx_theme.get_html_theme_path('stanford-theme')]

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
html_theme_path = os.path.join(BASE_DIR, 'story')
#html_theme_path = [os.path.join(BASE_DIR, 'story')]

html_theme = 'stanford_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = ['css/my.css']

latex_elements = {
    'inputenc': '',
    'utf8extra': '',
    'preamble': '''
\setotherlanguage{hindi}
\\newfontfamily\devanagarifont[Script=Devanagari]{Lohit Devanagari}
''',
}

latex_engine = 'xelatex'
